### ISSUE TITLE
ETC5523

### ISSUE THREAD

**Issue by emitanaka** [okayama1/Master-Business-analytics#1]
In the slides it says **ETC5523 Data story-telling** but is that meant to be **ETC5523 Communicating with Data**?

**Comment by okayama1** [comment]
I got the names from another presentation that was done on the master's before I did mine (I guess it is the same course, probably first had that name). I believe, that in the next weeks all the info will be on the website and it will have the final names ETC5523 Communicating with Data.

**Comment by robjhyndman** [comment]
Emi is right -- it should be Communicating with data. The other name was an early proposal that must have still be in something I sent you.

**Comment by okayama1** [comment]
If that is the final name then I will update the presentation to reflect that :-)
